//controller function for user registration, login and user logout

import userModel from "../models/userModel.js";
import bcrypt from "bcrypt"; //encrypt password
import jwt from "jsonwebtoken"; //generate token for user authentication

const registerUser = async (req,res)=>{
  try{

    const {name,email,password} = req.body;
    //check if user already exists
    if(!name || !email || !password){
      return res.json({success:false,message:"Missing required fields"});
    }

    //encrypt password

    const salt = await bcrypt.genSalt(10);  //moderate level of encryption more val means more secure but slow

    const hashedPassword = await bcrypt.hash(password,salt);

    const userData = {
      name,
      email,
      password : hashedPassword
    }

    const newUser = new userModel(userData);  //create new user 

    const user = await newUser.save(); // save to the database

    const token = jwt.sign({id:user._id},process.env.JWT_SECRET) //_id is auto generated by mongoDB

    res.json({success:true,token,user:{name:user.name}})
    

  }catch(error){
    console.log(error);
    res.json({success:false,message:error.message})
  }

}


const loginUser = async(req,res) =>{
  try{
    const{email,password} = req.body;

    const user = await userModel.findOne({email}); //find user by email

    if(!user){
      return res.json({success:false,message:"User not found"});
    }

    const isMatch = await bcrypt.compare(password, user.password); //compare entered password with hashed password

  if(isMatch){
    
    const token = jwt.sign({id:user._id},process.env.JWT_SECRET) //_id is auto generated by mongoDB
    return res.json({success:true,token,user:{name:user.name}}); //return token and user name

  }else{
    return res.json({success:false,message:"Invalid credentials"});
  }

  }catch(error){
    console.log(error);
    res.json({success:false,message:error.message})
  }
}

const userCredits = async(req,res)=>{
  try{
    // const {userId} = req.body; //using middleware we can get userId 

    const {userId} = req.user;

    const user = await userModel.findById(userId);
    res.json({success:true,credit : user.creditBalance,user:{name : user.name}});

  }catch(error){
    console.log(error);
    res.json({success:false,message:error.message});
  }
}



export  {registerUser,loginUser,userCredits};